# Generated by Django 6.0.2 on 2026-02-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('settore', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('crediti', models.IntegerField(default=6)),
                ('professore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi_insegnati', to='api.professore')),
                ('studenti', models.ManyToManyField(blank=True, related_name='corsi_seguiti', to='api.studente')),
            ],
        ),
    ]
