# Generated by Django 6.0.2 on 2026-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('stato_operativo', models.BooleanField(default=True)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
