# Generated by Django 6.0.2 on 2026-02-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('piano', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='luogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivi', to='api.luogo'),
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('descrizione_intervento', models.TextField()),
                ('data_intervento', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='api.dispositivo')),
            ],
        ),
    ]
