# Generated by Django 6.0.2 on 2026-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_luogo_dispositivo_luogo_manutenzione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versione', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='software_installati',
            field=models.ManyToManyField(blank=True, related_name='dispositivi', to='api.software'),
        ),
    ]
